require 'nokogiri'
require 'rest_client'
require 'eventmachine'
require 'em-http-request'
require 'base64'
require 'set'
require 'fileutils'
require 'digest/sha1'
require 'json'
require 'tempfile'
require 'tmpdir'

require_relative 'just_crawl/version'
require_relative 'just_crawl/engine'
require_relative 'just_crawl/string'
require_relative 'just_crawl/failure'
require_relative 'just_crawl/register'
require_relative 'just_crawl/page'
